### ISSUE TITLE
Windows 10 Problem

### ISSUE THREAD

**Issue by eastbloodacar24** [cydolo/AGodZilla#30] opened 2019-04-08 18:38 UTC
I'm getting error on load.

@Windows 10, 16299, 2016 Final Version (i did not updated due Microsoft's software problems.)

Installed .NET Framework : 4.7.2 

System.IO.FileNotFoundException: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' file or integrated code or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by cydolo** [comment] 2019-04-08 20:26
Check for updates in Windows 10

**Comment by eastbloodacar24** [comment] 2019-04-08 22:18
i think it is file related problem, i found majority of dll files but i could not find flurl http dll(s).

can you give me list of needed dll files or direct link of them?

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.String> Flurl.Http.GeneratedExtensions.GetStringAsync(System.String, System.Threading.CancellationToken, System.Net.Http.HttpCompletionOption)'.

**Comment by cydolo** [comment] 2019-04-08 22:19
do you use the newest version 3.2.0?

**Comment by eastbloodacar24** [comment] 2019-04-08 22:23
yes, i tried newest (3.2.0)/old (2.2) version but same.

i found dll files in same RAR file with old version of program.

**Comment by cydolo** [comment] 2019-04-08 22:26
the dll files are merged delete all the files out and download AGodZilla again

**Comment by eastbloodacar24** [comment] 2019-04-08 22:29
emm i already tried that.

**Comment by cydolo** [comment] 2019-04-08 22:32
The problem is more because you may not have the right framework installed or windows 10 update still open
connect to our discord and you will be helped
https://discord.gg/ZwgMfNz

**Closed** 2019-04-09 18:42 UTC
